apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentnginx1
  namespace: sankfux
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: nginx
        name: mynginx
